---
title: "Response to Review"
---

JSS 4108:

Nicholas John Tierney, Dianne Cook

Expanding tidy data principles to facilitate missing data exploration, visualization and assessment of imputations

---------------------------------------------------------
For further instructions on JSS style requirements please see the Style Files (in particular section 2.1 Style Checklist of jss.pdf) and FAQ at http://www.jstatsoft.org/about/submissions.

For further examples please see RECENT JSS papers.
---------------------------------------------------------

From the editorial team:

We apologize for the additional delays in processing 
your submission due to the COVID-19 pandemic.

The submission "Expanding tidy data principles to facilitate missing data
exploration, visualization and assessment of imputations" presents the R 
package naniar which provides data structures, summaries and visualizations 
for missing data.

Additional comments:

Please add some discussion on what kind of functionality is available in 
other statistical software packages than R in order to better embed the 
contribution not only within R, but the statistical software ecosystem in 
general.

> We have added the following at the end of section 3:

> Missing data can be explored and visualised in other software such as \proglang{STATA}, \proglang{SAS}, and \proglang{SPSS}. They provide basic table frequencies of missing data, and basic visualisations on missingness patterns. However, none of these software provide functions to specifically visualise missing values in bivariate or multivariate settings, and it is only possible to visualise missing values after performing data analysis, counting and summarising missingness. Imputation methods from mean to regression, EM, and multiple imputation are all available, with out of the box diagnostics provided to assist comparing imputations. \proglang{python} also provides exploratory data analysis for missing data within \pkg{missingno} [@Bilogur2018], and the \pkg{scikit-learn} package provides imputation methods [@scikit-learn].

Please provide a plain R script which when run reproduces all results 
presented in the manuscript. In general purling the Rmd file and editing 
the resulting R file  slightly in order to guide the user what each block 
does, removing knitr specific content,   etc. is suitable.

> We have added a file, "tidy-missingdata-paper.R" that contains the R code from the paper

* The JSS style (https://www.jstatsoft.org/pages/view/style) should be 
followed more closely, especially using the title vs. sentence case, 
JSS-specific markup (\proglang, \pkg), and improving the BibTeX file. Some 
aspects of the style are handled incorrectly by "rticles", though (see
https://github.com/rstudio/rticles/issues/254).

> I have updated to the latest rticles package and checked that the JSS-specific markup has been fixed in the latest submission. Many instances of \proglang, \pkg, and \code have been used now

* Note that the affiliation of the second author is misspelled.

> We have fixed the affiliation of the second author

Manuscript style comments:

o For the code layout in R publications, we typically distinguish input/output using Sinput/Soutput (or equivalently CodeInput/CodeOutput). Unless there are special reasons to format it differently, the input should use the text width (up to 76 or 77 characters) and be indented by two spaces, e.g.,

begin{Sinput}
R> example_model <- lm(response ~ variable1 + variable2 + variable3, 
+    weights = w, data = mydata)
\end{Sinput}

> I believe this has been resolved with the latest update to rticles.

o If using "e.g." and "i.e." add a comma after the period to keep LaTeX from interpreting them as the end of a sentence, i.e.: "e.g., " and "i.e., ".

> Instances of `e.g.` have been replaced with `e.g.,`. 

o The rule for capitalizing the starting letters of Figure, Section and Table is as follows: If you are referring to a particular figure/section/table then capitalize the first letter, otherwise use a lower-case first letter. For example, something shown in Section 4 vs. there are three sections in this paper.

> Appropriate instances of `section` and `figure` have been replaced with `Section` and `Figure`.

o All captions should appear below the corresponding figure/table. The captions should be in sentence style and end with a period.  No additional formatting (such as \emph, f or \it) should be used for the caption.

> Captions are below every figure, and for each table these will be moved manually in the LaTeX output.

o All table row/column headers should also be in sentence style. There should not be further footnote-style annotations in tables; these should all be placed in the caption.

> Need to double check about headings here for tables - Di should I change things like "n_miss" to "Num. Missing" ?

o As a reminder, please make sure that:
	- \proglang, \pkg and \code have been used for highlighting throughout the paper (including titles and references), except where explicitly escaped.

> This has been done except for titles and references.

References:


o Journal of the Royal Statistical Society B (not: Journal of the Royal Statistical Society, Series B)
	the EM Algorithm.” Journal of the Royal Statistical Society. Series B
the EM Algorithm.” Journal of the Royal Statistical Society. Series B
o Springer-Verlag (not: Springer)
	and GGobi. 1st edition. Springer Publishing Company, Incorporated.


o Please make sure that all software packages are \cite{}'d properly.
o All references should be in title style.
o See FAQ for specific reference instructions.


Code:

o Please make sure that the files needed to replicate all code/examples within the manuscript are included in a standalone replication script.

Other notes

- Check references are correctly referred using \pkg and \proglang
- Check references are correctly referred to in text
- Read over actual references compiled in the PDF - e.g., Adrian Barnett's article has a random string at the end.
- Check quotes (" and ') are facing the right way
- Don't start a sentence with a capital letter for pkgs.
- Fix tables 4 and 5, ensure all appropriate tables have
- Check that text overflows correctly.
